language: C

compiler:
  - gcc

before_install:
  - pip install --user cpp-coveralls
  - git clone https://github.com/connectFree/everip.git
  - git clone https://github.com/connectFree/libre.git
  - git clone https://github.com/connectFree/libsodium.git

install:
  - cd libre
  - STATIC=1 USE_OPENSSL= make
  - cd ../libsodium
  - ./autogen.sh
  - ./configure --prefix=$PWD/../build_libsodium --disable-shared
  - make
  - make install
  - cd ../everip

script:
  - GCOV=1 SIGNED_CLA_LICENSE=1 LIBSODIUM_PATH=../build_libsodium make test

after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
  - curl https://copilot.blackducksoftware.com/scripts/init/gradle -o bds_init.gradle
  - ./gradlew --init-script bds_init.gradle buildBom -DbdsPluginVersion=5.0.2
  - bash <(curl -s https://copilot.blackducksoftware.com/bash/travis) ./build/blackduck/*_bdio.jsonld
